Django_server/Django_server/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
      path('admin/', admin.site.urls),
      path('store/', include('store.urls')),
      path('api/', include('store.urls_api')),
      path('ws/', include('cl_server.urls')),
      ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_server/cl_server/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

Django_server/store/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import ProductListView
from .views import ProductDetailView
from .views import ProductDetailRedirect


app_name = 'products'


urlpatterns = [
    path(
        'product/<int:pk>/',
        ProductDetailRedirect.as_view(),
        name='product_redirect'
    ),
    path(
        'products/',
        cache_page(600)(ProductListView.as_view()),
        name='products'
    ),
    path(
        'product/<int:pk>-<str:slug>/',
        cache_page(600)(ProductDetailView.as_view()),
        name='product-detail'
    ),
]

Django_server/store/models.py
from django.db import models
from django.urls import reverse
# from django.utils.text import slugify
from uuslug import slugify
from sorl.thumbnail import ImageField


class Product(models.Model):
    product_name = models.CharField(
        max_length=255,
        verbose_name='Название товара'
    )
    product_price = models.FloatField(
        max_length=50,
        verbose_name='Цена товара'
    )
    value_discount = models.ForeignKey(
        'Discount',
        on_delete=models.SET_DEFAULT, default='0',
        verbose_name='% скидки',
        blank=True,
        null=True,
    )
    discount_price = models.FloatField(
        max_length=150,
        verbose_name='Цена со скидкой',
        blank=True,
        default='0'
    )
    product_image = models.ImageField(
        upload_to='uploads/images',
        blank=True,
        null=True,
        verbose_name='Фотография товара'
    )
    slug = models.SlugField(
        default='',
        editable=False,
        max_length=150
    )

    def get_absolute_url(self):
        # return reverse('products:product-detail', args=[str(self.id)])
        kwargs = {
            'pk': self.id,
            'slug': self.slug
        }
        return reverse('products:product-detail', kwargs=kwargs)

    @property
    def image_url(self):
        if self.product_image and hasattr(self.product_image, 'url'):
            return self.product_image.url

    def save(self, *args, **kwargs):
        value = self.product_name
        self.slug = slugify(value)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.product_name


class Discount(models.Model):
    value = models.IntegerField(
        verbose_name='Процент скидки'
    )

    # def __int__(self):
    #     return self.id

    def __str__(self):
        return f'Скидка {self.value}'

Django_server/store/forms.py
from django import forms


class ProductForm(forms.Form):
    product_price_max = forms.FloatField()
    product_price_min = forms.FloatField()

Django_server/cl_server/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

Django_server/store/views.py
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic.edit import FormView
from django.views.generic.base import RedirectView
from django.shortcuts import reverse


from .forms import ProductForm
from .models import Product


class ProductListView(ListView, FormView):
    model = Product
    context_object_name = 'products'
    template_name = 'product_list.html'
    form_class = ProductForm
    success_url = '/api/products/all/'
    paginate_by = 5

    def get_queryset(self):
        price_min = self.request.GET.get('min', '0')
        price_max = self.request.GET.get('max', '10000')
        new_context = Product.objects.filter(product_price__range=[
            price_min, price_max
        ])

        return new_context

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context['min'] = self.request.GET.get('price_min', '0')
        context['max'] = self.request.GET.get('price_max', '10000')
        return context


class ProductDetailView(DetailView):
    model = Product
    query_pk_and_slug = True
    context_object_name = 'product'
    template_name = 'product_detail.html'


class ProductDetailRedirect(RedirectView):
    permanent = True

    def get_redirect_url(self, pk):
        product = Product.objects.get(pk=pk)
        slug = product.slug
        return reverse('products:product-detail', args=(pk, slug))

Django_server/cl_server/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Channel room</title>
</head>
<body>
    <div class="#data_message">Hi there!</div>><br>
    <script>
        const messageSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/server'
            + '/'
        );
        messageSocket.onmessage = function(event) {
            alert(`Данные получены: ${event.data}`);
        }

    </script>

</body>
</html>

Django_server/store/templates/product_detail.html
{% load thumbnail %}
{{ product.product_name }} ({{ product.product_price }})<br><br>
{% thumbnail product.product_image "250x250" crop="center" as im %}
    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">  250x250
{% endthumbnail %}<br><br>
{% thumbnail product.product_image "600x600" crop="center" as im %}
    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">  600x600
{% endthumbnail %}<br><br>
<img src="{{ product.image_url }}">  original

Django_server/store/templates/product_list.html
{% load my_tags %}
{% for product in products %}
      <li>
        <a href="{{ product.get_absolute_url }}">{{ product.product_name }}</a>
          ({{product.product_price}})
      </li>
{% endfor %}
{% if is_paginated %}
  {% if page_obj.has_previous %}
    <a href="?{% param_replace page=1 %}">First</a>
    {% if page_obj.previous_page_number != 1 %}
      <a href="?{% param_replace page=page_obj.previous_page_number %}">Previous</a>
    {% endif %}
  {% endif %}

  Page {{ page_obj.number }} of {{ paginator.num_pages }}

  {% if page_obj.has_next %}
    {% if page_obj.next_page_number != paginator.num_pages %}
      <a href="?{% param_replace page=page_obj.next_page_number %}">Next</a>
    {% endif %}
    <a href="?{% param_replace page=paginator.num_pages %}">Last</a>
  {% endif %}

  <p>Objects {{ page_obj.start_index }}—{{ page_obj.end_index }}</p>
{% endif %}
<div>
    <form method="get" action="{% url 'products:products' %}">
    <p>Price min: <input type="text" value={{min}} name="min"/></p>
    <p>Price max: <input type="text" value={{max}} name="max"/></p>
    <p><input type="submit" name="submit" value="submit"/></p>
</form>
</div>